from core import MarketConfig


CONFIG = MarketConfig(
    name="United States",
    market_code="US",
    site_base_url="https://www.uniqlo.com/us/en",
    api_base_url="https://www.uniqlo.com/us/api/commerce/v5/en",
    client_id="uq.us.web-spa",
    accept_language="en-US,en;q=0.9",
    currency_code="USD",
    price_prefix="$",
    price_decimals=2,
    category_routes=(
        "men/outerwear-and-blazers",
        "men/tops",
        "men/shirts-and-polos",
        "men/sweaters",
        "men/bottoms",
        "men/innerwear",
        "men/loungewear-and-home",
        "men/accessories-and-shoes",
        "women/outerwear-and-blazers",
        "women/tops",
        "women/shirts-and-blouses",
        "women/sweaters",
        "women/bottoms",
        "women/dresses-and-skirts",
        "women/innerwear",
        "women/loungewear-and-home",
        "women/accessories-and-shoes",
        "kids/outerwear-and-blazers",
        "kids/tops",
        "kids/sweaters",
        "kids/shirts-and-blouses",
        "kids/bottoms",
        "kids/dresses",
        "kids/innerwear",
        "kids/accessories",
    ),
)
