from core import MarketConfig


CONFIG = MarketConfig(
    name="Canada",
    market_code="CA",
    site_base_url="https://www.uniqlo.com/ca/en",
    api_base_url="https://www.uniqlo.com/ca/api/commerce/v5/en",
    client_id="uq.ca.web-spa",
    accept_language="en-CA,en;q=0.9",
    currency_code="CAD",
    price_prefix="CA $ ",
    price_decimals=2,
    category_routes=(
        "men/tops",
        "men/outerwear",
        "men/sweaters-and-knitwear",
        "men/shirts-and-polo-shirts",
        "men/bottoms",
        "men/innerwear-and-base-layers",
        "men/loungewear",
        "men/accessories-and-home",
        "women/outerwear",
        "women/tops",
        "women/sweaters-and-knitwear",
        "women/shirts-and-blouses",
        "women/bottoms",
        "women/innerwear",
        "women/loungewear-and-homeware",
        "women/accessories-and-home",
        "kids/tops",
        "kids/bottoms",
        "kids/shirts-and-knitwear",
        "kids/outerwear",
        "kids/dresses-and-jumpsuits",
        "kids/innerwear-and-base-layers",
        "kids/accessories",
    ),
)
