from core import MarketConfig


CONFIG = MarketConfig(
    name="United Kingdom",
    market_code="GB",
    site_base_url="https://www.uniqlo.com/uk/en",
    api_base_url="https://www.uniqlo.com/uk/api/commerce/v5/en",
    client_id="uq.gb.web-spa",
    accept_language="en-GB,en;q=0.9",
    currency_code="GBP",
    price_prefix="£",
    price_decimals=2,
    category_routes=(
        "men/outerwear",
        "men/tops",
        "men/jumpers",
        "men/shirts-and-polos",
        "men/bottoms",
        "men/innerwear",
        "men/loungewear-and-homeware",
        "men/accessories",
        "women/outerwear",
        "women/tops",
        "women/jumpers",
        "women/shirts-and-blouses",
        "women/bottoms",
        "women/skirts-and-dress",
        "women/innerwear",
        "women/loungewear-and-homeware",
        "women/accessories",
        "kids/outerwear",
        "kids/tops",
        "kids/bottoms",
        "kids/dresses-and-jumpsuits",
        "kids/innerwear",
        "kids/accessories",
    ),
)
