from core import MarketConfig


CONFIG = MarketConfig(
    name="Japan",
    market_code="JP",
    site_base_url="https://www.uniqlo.com/jp/ja",
    api_base_url="https://www.uniqlo.com/jp/api/commerce/v5/ja",
    client_id="uq.jp.web-spa",
    accept_language="ja-JP,ja;q=0.9",
    currency_code="JPY",
    price_prefix="¥",
    price_decimals=0,
    category_routes=(
        "men/outerwear",
        "men/tops",
        "men/sweaters",
        "men/shirts-and-polo-shirts",
        "men/bottoms",
        "men/innerwear",
        "men/loungewear-and-homeware",
        "men/accessories",
        "women/outerwear",
        "women/tops",
        "women/sweaters",
        "women/shirts-and-blouses",
        "women/bottoms",
        "women/dresses-and-skirts",
        "women/innerwear",
        "women/loungewear-and-homeware",
        "women/accessories",
        "kids/outerwear",
        "kids/tops",
        "kids/sweaters-and-shirts",
        "kids/bottoms",
        "kids/dresses-and-jumpsuits",
        "kids/innerwear",
        "kids/loungewear-and-homeware",
        "kids/accessories",
    ),
)
